CREATE TABLE [dbo].[LUT_BASETYPE] (
    [ID]               INT NOT NULL,
    [NAME]             VARCHAR (50) NULL,
    [NAME_LONG]        VARCHAR (99) NULL,
    [DESCRIPTION]      VARCHAR (250) NULL,
    [MODIFY_TIMESTAMP] VARCHAR (20) NULL,
    CONSTRAINT [PK_LUT_BASETYPE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

