CREATE TABLE [dbo].[BikeHike] (
    [USE_ID]         INT            NOT NULL,
    [USE_ACCESS_TOW] INT            NULL,
    [USE_ACCESS_BKW] INT            NULL,
    [BIKESIGNEDTOW]  DECIMAL (1)    NULL,
    [BIKESIGNEDBKW]  DECIMAL (1)    NULL,
    [BIKEFEATURETOW] NVARCHAR (254) NULL,
    [BIKEFEATUREBKW] NVARCHAR (254) NULL,
    CONSTRAINT [FK_BikeHike_LinkUse] FOREIGN KEY ([USE_ID]) REFERENCES [dbo].[LinkUse] ([USE_ID]),
    UNIQUE NONCLUSTERED ([USE_ID] ASC)
);

