CREATE TABLE [dbo].[LUT_BIKEMERKMAL] (
    [ID]               NVARCHAR(254) NOT NULL,
    [NAME]             VARCHAR (99) NULL,
    [NAME_LONG]        VARCHAR (99) NULL,
    [DESCRIPTION]      VARCHAR (99) NULL,
    [MODIFY_TIMESTAMP] VARCHAR (20) NULL, 
    CONSTRAINT [PK_LUT_BIKEMERKMAL] PRIMARY KEY ([ID]) 
);

