CREATE TABLE [dbo].[LUT_BASETYPE] (
    [bt_ID]            INT NOT NULL,
    [NAME]             VARCHAR (50) NULL,
    [NAME_LONG]        VARCHAR (50) NULL,
    [DESCRIPTION]      VARCHAR (250) NULL,
    [MODIFY_TIMESTAMP] VARCHAR (50) NULL,
    CONSTRAINT [PK_LUT_BASETYPE] PRIMARY KEY CLUSTERED ([bt_ID] ASC)
);

