CREATE LOGIN [GIPadmin]
    WITH PASSWORD = N'y+q%PXyvZp,Tzsnihyi:rrgRmsFT7_&#$!~<vyiy gMLyl1&', SID = 0xCD8ADF78F3EC7A4FBD0247BA3727943C, DEFAULT_DATABASE = [GIPrva], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

